### ISSUE TITLE
Build error gcc4.8.4

### ISSUE THREAD

**Issue by DavidPoliakoff** [nvpro-pipeline/vkcpp#109]
Hey guys, following your build instructions, and I get

/home/david/Downloads/vkcpp/VkCppGenerator.cpp: In function ‘int main(int, char**)’:
/home/david/Downloads/vkcpp/VkCppGenerator.cpp:2881:33: error: no matching function for call to ‘std::list<DependencyData>::erase(std::list<DependencyData>::const_iterator&)’
     vkData.dependencies.erase(it);

Using an iterator instead of a const_iterator fixes the problem, I'll be doing that locally, but wanted to make you aware of the problem

**Comment by asuessenbach** [comment]
This project needs C++11 support, like described here: #70.

**Comment by DavidPoliakoff** [comment]
In that case why don't we try adding a SET(CMAKE_CXX_STANDARD c++11) to the CMakeLists.txt?

https://cmake.org/cmake/help/v3.1/variable/CMAKE_CXX_STANDARD.html

I've read that it's a bit of a legal pain to do a PR or I'd do it myself

Thanks!

**Comment by mtavenrath** [comment]
We're already doing this: https://github.com/nvpro-pipeline/vkcpp/blob/master/CMakeLists.txt#L67 like here: https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD
