### ISSUE TITLE
SemaphoreCreateFlagBits empty

### ISSUE THREAD

**Issue by ocirne23** [nvpro-pipeline/vkcpp#111]
https://github.com/nvpro-pipeline/vkcpp/blob/master/vulkan/vk_cpp.hpp#L632

c api equivalent;

    VkSemaphoreCreateInfo presentCompleteSemaphoreCreateInfo = {};
    presentCompleteSemaphoreCreateInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
    presentCompleteSemaphoreCreateInfo.pNext = NULL;
    presentCompleteSemaphoreCreateInfo.flags = VK_FENCE_CREATE_SIGNALED_BIT;

but

    vk::SemaphoreCreateInfo presentCompleteSemaphoreCreateInfo = vk::SemaphoreCreateInfo()
        .setFlags(vk::SemaphoreCreateFlagBits::eSignaled);

eSignaled does not exist, passing in vk::FenceCreateFlagBits doesn't work either.

**Comment by asuessenbach** [comment]
I'd consider this an error:

`presentCompleteSemaphoreCreateInfo.flags = VK_FENCE_CREATE_SIGNALED_BIT;`

There are no flags defined for the VkSemaphoreCreateFlags, and VK_FENCE_CREATE_SIGNALED_BIT is a VkFenceCreateFlagBits. Those two things are not compatible, but that can't be detected with C.
But the C++ wrapper reveals that error.

**Comment by ocirne23** [comment]
Fair enough, I copied samples from https://github.com/SaschaWillems/Vulkan but they seem to have corrected that error in the meantime :). Nevermind!
