### ISSUE TITLE
Make exceptions optional

### ISSUE THREAD

**Issue by smellslikedonkey** [nvpro-pipeline/vkcpp#112]
Hi,

I have a suggestion for you on a possible way to make exceptions optional in enhanced mode. Basically I'd suggest wrapping the return type and the throw in macros that can be redefined something like this: 

```
#ifndef VK_ERROR
#define VK_THROWS(TYPE) TYPE
#define VK_ERROR(RES,STR) throw std::system_error(RES,STR);
#endif
```

Then functions that throw would look like this:
```
    VK_THROWS(void) begin( const CommandBufferBeginInfo & beginInfo ) const
    {
      Result result = static_cast<Result>( vkBeginCommandBuffer( m_commandBuffer, reinterpret_cast<const VkCommandBufferBeginInfo*>( &beginInfo ) ) );
      if ( result != Result::eSuccess )
      {
        VK_ERROR( result, "vk::CommandBuffer::begin" );
      }
    }
```

This would allow developers to just log instead or use another error handling pattern like "Expected":
https://channel9.msdn.com/Shows/Going+Deep/C-and-Beyond-2012-Andrei-Alexandrescu-Systematic-Error-Handling-in-C

The details don't really matter to me but if I can leave exception off, I'd be happy!

(BTW great library)

**Comment by mtavenrath** [comment]
@smellslikedonkey Optional exceptions is something we've already been working on. Have a look at pull request #110.

**Comment by mtavenrath** [comment]
Exceptions are not optional, closing.
