### ISSUE TITLE
If a flag type has no bits, functions which take that flag type should have a default parameter for the flag argument

### ISSUE THREAD

**Issue by jherico** [nvpro-pipeline/vkcpp#115]
` ... Device::mapMemory( ..., MemoryMapFlags flags ) const`

should be

`... Device::mapMemory( ..., MemoryMapFlags flags = MemoryMapFlags()) const`

**Comment by asuessenbach** [comment]
For flag types without any bit, you're not supposed to set any bit at all. That is, maybe we should just skip such a flag at all? That would work as well with flags that are not the last argument to the call.
Or would that deviate too much from the original call?

Any opinions on that?

**Comment by mtavenrath** [comment]
@jherico, for empty flags you can just pass {} instead of i.e. MemoryMapFlags(). Is this to unconvinient?

**Comment by jherico** [comment]
@asuessenbach my main concern with skipping flags entirely is that if flags are eventually added then the function signature has to change and you've potentially broken existing code.  

@mtavenrath I'll keep that in mind, but as I said on #113 I have to wonder why the API wouldn't be aiming to provide the absolute least burden on clients.  Having to type `method(args, {})` every single time is more convenient than `method(args, MethodFlags())`, but still less convenient than `method(args)`, and in the absence of a good reason **not** to provide a default parameter, I can't imagine why you wouldn't

**Comment by andrewjw1995** [comment]
@jherico does it matter so much if the function signature is different? It is C++, so there is always the option of providing an overload
