### ISSUE TITLE
vkcpp missing many stl headers it depends on 

### ISSUE THREAD

**Issue by jherico** [nvpro-pipeline/vkcpp#117]
The vkcpp header should include all it's own dependencies directly.  Attempting to use it on an Ubuntu system caused compilation failures due to missing definitions for `std::find` and others.

As far as I can tell, all of the following headers should be explicitly used

```
#include <cstddef>
#include <algorithm>
#include <initializer_list>
#include <memory>
#include <type_traits>
```

**Comment by mtavenrath** [comment]
Fixed in Vulkan-Hpp
