### ISSUE TITLE
ArrayProxy does not compile in non-enhanced mode

### ISSUE THREAD

**Issue by BigBigos** [nvpro-pipeline/vkcpp#125]
ArrayProxy uses std::vector which is not included when VKCPP_DISABLE_ENHANCED_MODE is defined.

Since ArrayProxy is used only in enhanced mode, simple #ifndef VKCPP_DISABLE_ENHANCED_MODE/#endif around class ArrayProxy definition suffices to fix this problem.

**Comment by mtavenrath** [comment]
Fixed in Vulkan-Hpp

**Comment by oceantume** [comment]
I just realized Vulkan-Hpp existed after searching for this issue. If it has become the main repository for this project it may be a good idea to add a notice on here! Thanks a lot!
