### ISSUE TITLE
VK_IMAGE_LAYOUT_PRESENT_SRC_KHR missing from vk::ImageLayout

### ISSUE THREAD

**Issue by Trevin** [nvpro-pipeline/vkcpp#13]
It is easy enough to work around but breaks from the expected enum usage.

**Comment by mtavenrath** [comment]
The generator is missing the enum extends mechiansm of extensions. We're working on that feature.

**Comment by mtavenrath** [comment]
Enums specified in extensions will now be generated. Closing.
