### ISSUE TITLE
error C3861: 'assert': identifier not found

### ISSUE THREAD

**Issue by gartenriese2** [nvpro-pipeline/vkcpp#14]
When compiling with Visual Studio 2015 it doesn't compile because of the error mentioned in the title. Maybe add `#include <cassert>`?

**Comment by mtavenrath** [comment]
Do you see the error when compiling VkCppGenerator.cpp or when using vk_cpp.h?

**Comment by gartenriese2** [comment]
Ah, sorry, I am only using vk_cpp.h, forgot to mention that.

**Comment by mtavenrath** [comment]
Please verify that adding #include <cassert> before #include <cstdin.h> fixes your issue.

**Comment by gartenriese2** [comment]
What do you mean? I added `#include <cassert>` and it compiles without any errors now.

**Comment by mtavenrath** [comment]
Yes, the comment function ate the symbols. I'll add the line to the generator.

**Comment by mtavenrath** [comment]
Issue fixed, closing.
