### ISSUE TITLE
Result enum missing?

### ISSUE THREAD

**Issue by gartenriese2** [nvpro-pipeline/vkcpp#15]
I have a helper function to convert `Result` objects to strings:

```
const std::string vkResultToString(const vk::Result & result) {
	switch (result)	{
		case vk::Result::eVkSuccess:
			return "Success";
			break;
		case vk::Result::eVkNotReady:
			return "Not ready";
			break;
		case vk::Result::eVkEventSet:
			return "Event set";
			break;
		case vk::Result::eVkEventReset:
			return "Event reset";
			break;
		case vk::Result::eVkIncomplete:
			return "Incomplete";
			break;
		case vk::Result::eVkErrorOutOfHostMemory:
			return "Error: Out of host memory";
			break;
		case vk::Result::eVkErrorOutOfDeviceMemory:
			return "Error: Out of device memory";
			break;
		case vk::Result::eVkErrorInitializationFailed:
			return "Error: Initialization failed";
			break;
		case vk::Result::eVkErrorDeviceLost:
			return "Error: Device lost";
			break;
		case vk::Result::eVkErrorMemoryMapFailed:
			return "Error: Memory map failed";
			break;
		case vk::Result::eVkErrorLayerNotPresent:
			return "Error: Layer not present";
			break;
		case vk::Result::eVkErrorExtensionNotPresent:
			return "Error: Extension not present";
			break;
		case vk::Result::eVkErrorFeatureNotPresent:
			return "Error: Feature not present";
			break;
		case vk::Result::eVkErrorIncompatibleDriver:
			return "Error: Incompatible driver";
			break;
		case vk::Result::eVkErrorTooManyObjects:
			return "Error: Too many objects";
			break;
		case vk::Result::eVkErrorFormatNotSupported:
			return "Error: Format not supported";
			break;
		case vk::Result::eVkTimeout:
			return "Timeout";
			break;
		default:
			return "NOT_DEFINED";
	}
}
```

I compared these with all possible Result enums and I don't think there are any missing. However I still get a `NOT_DEFINED` returned from my `vk::createImage` call.

**Comment by mtavenrath** [comment]
Did you check the return value? There're drivers which have additional enums in the -1000 range.

**Comment by gartenriese2** [comment]
I get the value -1000013000. Is there a list of all the possible values somewhere?

**Comment by mtavenrath** [comment]
the wrapper is missing enums for extensions (issue #13). Though I haven't found -1000013000 anywhere in vulkan.h...

**Comment by mtavenrath** [comment]
Btw. we have something like toString(vkEnum) on our todo-list ;-)

**Comment by mtavenrath** [comment]
There're 3 enums from NVIDIA:
#define VK_ERROR_INVALID_SHADER_NV    VkResult(-1000012000)
which is part of VK_NV_glsl_shader, which is documented publically.

and two enums which are unofficial and will vanish most likely:
#define VK_ERROR_INVALID_PARAMETER_NV VkResult(-1000013000)
#define VK_ERROR_INVALID_ALIGNMENT_NV VkResult(-1000013001)

Do you use the validation layer? VK_ERROR_INVALID_ALIGNMENT_NV should have been caught by it.

**Comment by gartenriese2** [comment]
A `toString(vkEnum/vk::Result)` method would be a good idea :-)
Thanks for looking up the error code. Seems like I messed up with one or more parameters.
I don't use a validation layer yet, maybe I should ...

**Comment by mtavenrath** [comment]
Dup of issue #13 and drivers might return values not specified in the spec.

Closing.
