### ISSUE TITLE
Split big source file into components

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/vkcpp#24]
It might look convenient to publish [a single big source file for a promising class library](https://github.com/nvpro-pipeline/vkcpp/blob/ba67848d0ba1b7744eef50072678ddaa3c215324/vulkan/vk_cpp.h#L29 "Update candidate") at the beginning. I find it more useful to split it into a few parts.
* Can version checks (like [the used assertion](http://en.cppreference.com/w/cpp/language/static_assert "Static assertion")) be performed a bit earlier by including less source code?
* Will [derivation](https://en.wikipedia.org/wiki/Class_%28computer_programming%29 "Software development challenges around C++ class libraries") become eventually easier by more direct references to the preferred components?

Does the source file structure need any fine-tuning by advanced configuration of a software build system?

**Comment by mtavenrath** [comment]
For now we plan to stay with the single auto-generated vk_cpp.h header which is included in the git repository for convenience.

> Can version checks (like the used assertion) be performed a bit earlier by including less source code?
We can move the vulkan.h include and the assertion before the other includes

> Will derivation become eventually easier by more direct references to the preferred components?
Can you be more specific what you want to achieve?

**Comment by elfring** [comment]
I imagine that [the suggested improved source file structure](https://github.com/nvpro-pipeline/vkcpp/blob/ba67848d0ba1b7744eef50072678ddaa3c215324/VkCppGenerator.cpp#L1972 "Update candidate: Header file generation") will be published a few version numbers later then.
How much do you care for [source file granularity](https://en.wikipedia.org/wiki/Granularity#Computing "Granularity in software design")?

**Comment by elfring** [comment]
Can the grouping of application programming interfaces that is shown by [the document "Vulkan Online Quick Reference"](https://www.khronos.org/registry/vulkan/specs/1.0/refguide/Vulkan-1.0-web.pdf "Vulkan quick reference documentation") be considered as [a component structure](https://en.wikipedia.org/wiki/Component-based_software_engineering#Software_component "Selection of software components") which will become more useful also for [your software generation tool](https://github.com/nvpro-pipeline/vkcpp/blob/ba67848d0ba1b7744eef50072678ddaa3c215324/VkCppGenerator.cpp#L1912 "Update candidate: Header file generation")?

**Comment by mtavenrath** [comment]
If we would split the auto-generated header we'd split by classes we've introduced now, not by functions related to objects types which is impossible with the classes.

Due to the added complexity in the code generation and the simplified usage by including just a single header we're not going to split the header up into multiple pieces.

**Comment by elfring** [comment]
Would you ever like to use a generated C++ class without using any other stuff from this software?

Are there any design conflicts (or other special constraints) involved which hinder further improvements for the suggested class library evolution?
