### ISSUE TITLE
Configuration for external project dependencies

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/vkcpp#26]
1. The information "[Grab your favourite version vk.xml](https://github.com/nvpro-pipeline/vkcpp/blob/be14a994fb9ef5bb1d9807269b99c65659615400/README.md#usage "Software build description")" is provided in a document.
2. Another user is concerned about [the application of patches](https://github.com/nvpro-pipeline/vkcpp/issues/3 "Provide patch for API bug in XML file") for appropriate software dependencies.

How do you think about to express such details also by corresponding parameters and [the use of a CMake command like "ExternalProject_Add"](https://cmake.org/cmake/help/v3.5/module/ExternalProject.html "Management of external project settings") in [your build specification](https://github.com/nvpro-pipeline/vkcpp/blob/cd123067971f70d8a98cb135e4178c385fa62629/CMakeLists.txt#L27 "Update candidate: configuration checks")?

**Comment by mtavenrath** [comment]
The patch is no longer required and TinyXML is already built with the project. With regards to the vk.xml, since everyone might choose a different version there is no automation for now.
