### ISSUE TITLE
Improve version identification

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/vkcpp#28]
Would you like to [extend the specification of version information](https://cmake.org/cmake/help/v3.5/command/project.html "General project settings") for [the involved software components](https://github.com/nvpro-pipeline/vkcpp/blob/cd123067971f70d8a98cb135e4178c385fa62629/CMakeLists.txt#L27 "Build specification")?

**Comment by mtavenrath** [comment]
No.
