### ISSUE TITLE
CPack usage

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/vkcpp#29]
How do you think about to [reuse the software "CPack"](https://cmake.org/Wiki/CMake:Packaging_With_CPack "CMake: Packaging with CPack")?

**Comment by mtavenrath** [comment]
There's no real need for packaging of this Software yet. Closing.

**Comment by elfring** [comment]
Would you like to [support the installation of this software](https://cmake.org/Wiki/CMake:CPackPackageGenerators "Selection of package generators") anyhow?

**Comment by mtavenrath** [comment]
There's no need to install this software.
