### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/vkcpp#31]
Would you like to [wrap any application programming interfaces](http://en.cppreference.com/w/cpp/memory/unique_ptr "Extending application of smart pointers?") with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

**Comment by Phaeodaria** [comment]
There's no need for smart pointers at this level of the wrapper.

**Comment by mtavenrath** [comment]
There's no need for smart pointers in this API since it's doesn't allocate any plain pointers.

**Comment by elfring** [comment]
Does the application programming interface "Vulkan" provide any system resources which can be released in a safer way by [a combination of custom deleters](http://www.codeproject.com/Tips/459832/Unique-ptr-custom-deleters-and-class-factories "Unique_ptr custom deleters and class factories")?

**Comment by mtavenrath** [comment]
Yes, but this is out of the scope of this API due to the required amount of changes to the API interface 
and the resulting decreased efficiency. We're working on a prototype of a higher-level API on top of vkcpp which provides refcounting for vulkan handles.

**Comment by elfring** [comment]
I suggest to increase the abstraction level a bit so that it might become more convenient to use this application programming interface by appropriate C++ classes.
Do you see any further possibilities for improvements around memory allocation and release callback functions?

**Comment by elfring** [comment]
How useful would it be to [handle Vulkan resource allocation managers](https://en.wikipedia.org/wiki/Resource_allocation#Algorithms "Management of resource allocation") by smart pointers in C++?
