### ISSUE TITLE
Big problems with passing... (value is not same!)

### ISSUE THREAD

**Issue by acterhd** [nvpro-pipeline/vkcpp#33]
I have one problem and question. When I try pass CPP values to Vulkan example functions, I have errors. 

For example: 
```
VkPipelineStageFlags srcStageFlags = vk::PipelineStageFlagBits::eTopOfPipe;//VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
```

Have errors when try compile and even check.

**Comment by Phaeodaria** [comment]
This is supposed not to pass to get the desired type safety. Write the following code instead:

`vk::PipelineStageFlags srcStageFlags = vk::PipelineStageFlagBits::eTopOfPipe;//VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;`

**Comment by acterhd** [comment]
But is need pass to vanilla Vullkan functions?

**Comment by mtavenrath** [comment]
You can use a static_cast to get a vanilla enum:
      m_applicationInfo.sType = static_cast<VkStructureType>( sType );
