### ISSUE TITLE
In the enhanced functions, provide another function signature which pushes the `vk::AllocationCallbacks` parameter to the end and gives it a default value

### ISSUE THREAD

**Issue by jherico** [nvpro-pipeline/vkcpp#34]
In my code I have to create a 

`static vk::AllocationCallbacks DEFAULT_VK_ALLOC(nullptr, nullptr, nullptr, nullptr, nullptr, nullptr);`

and then call many functions like this...

`vk::createFence(device, vk::FenceCreateInfo(), DEFAULT_VK_ALLOC, fenceResult);`

It would be more convenient if there was an additional `createFence` with this signature

`Result createFence( Device device, const FenceCreateInfo& createInfo, Fence& fence, const AllocationCallbacks& allocator =  DEFAULT_VK_ALLOC)` along with a similar 'null allocator' declaration in the header file.

**Comment by mtavenrath** [comment]
Ordering the order of parameters is nothing we'd like to do in automatically generated code. It should be good enough to write <code>vk::createFence(device, vk::CreateInfo(), vk::AllocationCallbacks(), fenceResult)</code> with regards to code complexity.

Looking at the code we don't have a default constructor for non-CreateInfo structs yet. I'll put that on the TODO-list.

**Comment by mtavenrath** [comment]
@jherico, you can use vk::AllocationCallbacks::null() to pass no callbacks. The function order will not be changed since it's defined by the Vulkan specs.
