### ISSUE TITLE
Add enhanced forms that take a single object in addition to a vector object

### ISSUE THREAD

**Issue by jherico** [nvpro-pipeline/vkcpp#35]
In my code I have to create a 

`void cmdSetViewport( CommandBuffer commandBuffer, uint32_t firstViewport, std::vector<Viewport> const& viewports )`

could also be expressed as 

`void cmdSetViewport( CommandBuffer commandBuffer, uint32_t firstViewport, Viewport const& viewport)`, removing the need for me to create an extraneous `std::vector` if I only want to set one viewport.

**Comment by mtavenrath** [comment]
We've been discussing this feature and currently it's a pure performance thing. All you need is a pair of braces: <code>cmdSetViewport(cmdBuffer, first, {viewport})</code>

It's low prio on our list.

**Comment by mtavenrath** [comment]
@jherico, we've finally implemented this feature.
