### ISSUE TITLE
Enum naming for extensions

### ISSUE THREAD

**Issue by nyorain** [nvpro-pipeline/vkcpp#36]
For extensions the used string manipluation for enum value names does not work see e.g. PresentModeKHR:
```` cpp
enum class PresentModeKHR
{
    eVkPresentModeImmediateKhr = VK_PRESENT_MODE_IMMEDIATE_KHR,
    eVkPresentModeMailboxKhr = VK_PRESENT_MODE_MAILBOX_KHR,
    eVkPresentModeFifoKhr = VK_PRESENT_MODE_FIFO_KHR,
    eVkPresentModeFifoRelaxedKhr = VK_PRESENT_MODE_FIFO_RELAXED_KHR
};
````
The enum names do contain lots of redundant information. IMO, a KHR suffix instead of Khr would be nice, but that is not that important i guess. Expected behaviour would be probably something like this:
```` cpp
enum class PresentModeKHR
{
    eImmediateKHR = VK_PRESENT_MODE_IMMEDIATE_KHR,
    eMailboxKHR = VK_PRESENT_MODE_MAILBOX_KHR,
    eModeFifoKHR = VK_PRESENT_MODE_FIFO_KHR,
    eRelaxedKHR = VK_PRESENT_MODE_FIFO_RELAXED_KHR
};
````
You could fix this by checking if read enum value names are part of an extension (contain a tag suffix, which you either read from the specs or just use "KHR" and "EXT" at the moment) and treat them differently.

 If you consider this a real issue at all i could fix it and start a pull request.

**Comment by jherico** [comment]
I also find the existing enum name + enum value naming scheme tiresome when writing code, especially as it defeats code completion (in the abuve example I can't just type `eR` to jump to relaxed mode, I have to type `eVkPresentModeR`.  Not a huge fan of the `e` prefix either, but not as big a deal as the typename in the enum name.

**Comment by mtavenrath** [comment]
@nyorain, that's a good point remove the extension suffix from the enums, at least if they're not extending an enum like your PresentModeKHR example. Though I don't think it's a good idea when extending a non-extension enum like vk::Result::eVkErrorSurfaceLostKhr

@jherico, the 'e' prefix is a necessary evil introduced by enums which would start with a digit which require a prefix (1D, 2D, 3D). For consistency reasons we added the prefix everywhere.

With regards to extensions I'm wondering if it would be useful to move extensions to a separate namespace. In this case vk::PresentModeKHR::eXXX would get vk::khr::PresentMode

**Comment by nyorain** [comment]
Oh i did not mean to remove the KHR suffix (they are actually quite useful to see whether an enum value belongs to a extension or not and i think you should keep them everywhere for consistency). I rather meant to e.g. remove the `VkPresentMode` prefix for the enum values in my example and change `vk::PresentModeKHR::eVkPresentModeImmediateKhr` to `vk::PresentModeKHR::eImmediateKHR` since the old version is redundant and really annoying to type, as @jherico mentioned. 

Pull-request #37 fixes this issue.

The patch also fixes the `vk::Result` enum value naming, so it is e.g. `vk::Result::eSuccess` now instead of `vk::Result::eVkSuccess` since this was redundant.

I noticed that there are 2 tiny mistakes in the vk.xml specification which result in generated miss-namings for `vk::ColorSpaceKHR::eVkColorspaceSrgbNonlinearKHR` and `vk::StencilFaceFlagBits::eVkStencilFrontAndBack` but those are not codegen mistakes since they have simply wrong names in the specification.

**Comment by asuessenbach** [comment]
The commit listed above fixes this issue. It is similar to what nyorain proposed four days ago, but as mentioned in the readme (Due to the required paperwork please refrain from providing pull requests for simple changes and file an issue describing a bug or the desired change instead.) we decided to code that on our own. Nevertheless, thank you very much for your help.
