### ISSUE TITLE
Copyright notice contains "All rights reserved."

### ISSUE THREAD

**Issue by ahcox** [nvpro-pipeline/vkcpp#39]
Hi,

The project open source license grants the right to use the software but the copyright line immediately above the license contains a conflicting statement of "All rights reserved."

    // Copyright(c) 2015-2016, NVIDIA CORPORATION. All rights reserved.

I am not a lawyer but that phrase [seems to denote unlicensed software](http://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html):

>Brian Doll, GitHub's VP of Marketing, confirmed this arrangement is intentional:
>>Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.

**Comment by mtavenrath** [comment]
The license text sets out the terms under which the software can be used (here, a standard 3-clause BSD license).  NVIDIA remains the copyright holder in the [portions of the] software its employees created, which creates various rights under copyright law, including the right to actually enforce the terms of the software license.
