### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/vkcpp#40]
I find that an include guard like "[`VK_CPP_H_`](https://github.com/nvpro-pipeline/vkcpp/blob/524ebc9ff99ffac440d45f042754bac8f3b1383d/VkCppGenerator.cpp#L2627 "Reconsider identifier selection")" is too short for the safe reuse of header files (when they belong to an application programming interface).

**Comment by mtavenrath** [comment]
This is following the 'general' rule on how people usually define their header guards. We're not changing it unless we're colliding with another module.

**Comment by elfring** [comment]
I imagine that [a longer identifier will be generally safer](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Coherent naming scheme include guards") in such an use case.
