### ISSUE TITLE
Consider a method to check for null handles

### ISSUE THREAD

**Issue by pisiiki** [nvpro-pipeline/vkcpp#42]
Objects containing vulkan handles are tedious to check against VK_NULL_HANDLE:

`vk::CommandBuffer		m_SetupCmdBuffer;
if (  ((VkCommandBuffer&)m_SetupCmdBuffer) == VK_NULL_HANDLE  )`

maybe something like:

`if (  m_SetupCmdBuffer.isNullHandle()  )`

feels more natural and clean. In my opinion the user should be required to cast as little as possible.

Thanks.

**Comment by mtavenrath** [comment]
I think adding an explicit bool and operator !() would be even more natural. This would allow to write

if (m_setupCommandBuffer) {... }

and if (!m_commandBuffer) {...}

**Comment by pisiiki** [comment]
Sure, that would be better.

**Comment by mtavenrath** [comment]
We've implemented `explicit operator bool()` and `bool operator!() `for handles. You can now use` if (handle)` and` if (!handle)` in your code.
