### ISSUE TITLE
xcb_connection_t incomplete result type with VKCPP_ENHANCED_MODE enabled. !!EDIT!! Also with VK_USE_PLATFORM_XCB_KHR defined.

### ISSUE THREAD

**Issue by salamanderrake** [nvpro-pipeline/vkcpp#44]
I get

```vk_cpp.h:15191:22: error: incomplete result type 'xcb_connection_t' in function definition```

when enabling VKCPP_ENHANCED_MODE, this is with the latest master of vkcpp.

freshly generated vk_cpp.h with Vulkan-Docs 1.0-wsi_extensions branch, and your required fix in vk.xml file.

**Comment by mtavenrath** [comment]
@salamanderrake, do you see this issue only using the wsi_extension branch?

**Comment by salamanderrake** [comment]
@mtavenrath Yes I get the same issue with the 1.0 branch.

**Comment by mtavenrath** [comment]
@salamanderrake Do you use Windows or Linux?

**Comment by salamanderrake** [comment]
@mtavenrath Linux, sorry this is Ubuntu 15.10.

**Comment by mtavenrath** [comment]
@salamanderrake We'll try to reproduce on linux and see what's going on. It's possible vk.xml is missing a reference in the require section of the extension.

**Comment by mtavenrath** [comment]
@salamanderrake, I've compiled the following test-program without any issues on Ubuntu 15.10 using the latest vk_cpp.h and vulkan.h from github.

#define VKCPP_ENHANCED_MODE
#include <vulkan/vk_cpp.h>

int main(int argc, char *argv[])
{
}

**Comment by salamanderrake** [comment]
That does not look right, missing something after #include, unless that is a typo in your comment?

`#define VKCPP_ENHANCED_MODE

#include <vulkan/vulkan.h>
#include <vulkan/vk_cpp.h>
#include <iostream>

int main(int argc, char *argv[])
{
	std::cout << "Hello World!" << std::endl;
}
`

**Comment by salamanderrake** [comment]
You have to also define the VK_USE_PLATFORM_XCB_KHR macro.

With this on the command line:
```
clang++ --std=c++11 -I/usr/include -lvulkan main.cpp -o test -DVKCPP_ENHANCED_MODE -DVK_USE_PLATFORM_XCB_KHR
```
I get this:
```
In file included from main.cpp:5:
/usr/include/vulkan/vk_cpp.h:16828:22: error: incomplete result type
      'xcb_connection_t' in function definition
    xcb_connection_t getXcbPresentationSupportKHR( uint32_t queueFamilyI...
                     ^
/usr/include/xcb/xcb.h:104:16: note: forward declaration of 'xcb_connection_t'
typedef struct xcb_connection_t xcb_connection_t;  /**< Opaque structur...
               ^
In file included from main.cpp:5:
/usr/include/vulkan/vk_cpp.h:16830:97: error: use of undeclared identifier
      'connection'
  ...m_physicalDevice, queueFamilyIndex, &connection, visual_id );
                                          ^
2 errors generated.

```

**Comment by salamanderrake** [comment]
And with gcc/g++ I get this.

```
g++ --std=c++11 -I/usr/include -lvulkan main.cpp -o test -DVKCPP_ENHANCED_MODE -DVK_USE_PLATFORM_XCB_KHR
In file included from main.cpp:5:0:
/usr/include/vulkan/vk_cpp.h: In member function ‘xcb_connection_t vk::PhysicalDevice::getXcbPresentationSupportKHR(uint32_t, xcb_visualid_t) const’:
/usr/include/vulkan/vk_cpp.h:16829:5: error: return type ‘xcb_connection_t {aka struct xcb_connection_t}’ is incomplete
     {
     ^
/usr/include/vulkan/vk_cpp.h:16830:97: error: ‘connection’ was not declared in this scope
 viceXcbPresentationSupportKHR( m_physicalDevice, queueFamilyIndex, &connection,
```

**Comment by salamanderrake** [comment]
Clang Version.

```
clang++ --version
Ubuntu clang version 3.6.2-1 (tags/RELEASE_362/final) (based on LLVM 3.6.2)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

Gcc version.

```
g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mtavenrath** [comment]
The root cause for this behaviour is our ptr->reference conversion. xcb_connection_t is just meant to be used as pointer only outside of the library itself and thus there're no full declaration of the type.

We'll have to change the generator so that it returns a pointer to non-vulkan datatypes.

**Comment by mtavenrath** [comment]
The root cause for this behaviour is that we're converting the input value xcb_connection_t* to an output value which seems to be valid in all other cases.

In this case we've to keep the function as it is, but check for success to throw the exception.

**Comment by mtavenrath** [comment]
@salamanderrake,

we've changed the generator so that it doesn't change functions which don't return a result. Though the code still requires references, so that you have to dereference the xcb_connection when passing it to vkcpp functions.
