### ISSUE TITLE
Consider non-const references on getters.

### ISSUE THREAD

**Issue by pisiiki** [nvpro-pipeline/vkcpp#45]
If I'm not missing something while setting a field of a field on a vk object the user is confronted with a couple of choices:

```
// 1: Removing the const
const_cast<vk::ImageSubresourceRange&>(depthStencilView.subresourceRange()).aspectMask( vk::ImageAspectFlagBits::eDepth | vk::ImageAspectFlagBits::eStencil );

// 2: Creating a temporal object
vk::ImageSubresourceRange ISR;
ISR.aspectMask( vk::ImageAspectFlagBits::eDepth | vk::ImageAspectFlagBits::eStencil );
depthStencilView.subresourceRange(ISR);
```

I guess const refs are by design, however I don't see what harm could do returning non const refs given that the setters of the returned objects enforce the parameters themselves.

Thanks.

**Comment by mtavenrath** [comment]
As you're saying it quite uncomfortable to change values without the non-const versions of the getters. Especially for the flags it'd good to be able to write

depthStencilView.subresourceRange().aspectMask() |= vk::ImageAspectFlagBits::eDepth;

Thus we'll add the non-const versions of the getters in addition to the const versions.

**Comment by mtavenrath** [comment]
@pisiiki, we added non-const & getters in addition to the const & getters. Closing.

**Comment by pisiiki** [comment]
Thanks.
