### ISSUE TITLE
Header has unreferenced parameters

### ISSUE THREAD

**Issue by awesomekyle** [nvpro-pipeline/vkcpp#49]
When building with /W4 in Visual Studio and -wall in GCC, vk_cpp.h has unreferenced parameters in many of the [getString](https://github.com/nvpro-pipeline/vkcpp/blob/master/vulkan/vk_cpp.h#L18252) methods. These can be suppressed with a #pragma warning(disable), but ideally the header will compile without warnings by default.

**Comment by mtavenrath** [comment]
Fixed, closing.
