### ISSUE TITLE
Duplicate getResult(Result value)

### ISSUE THREAD

**Issue by Saulzar** [nvpro-pipeline/vkcpp#71]
When generated using the vulkan 1.0.5 vk.xml I get a vk_cpp.h with duplicate Result type.

In file included from test.cpp:2:0:
vk_cpp.h:11021:14: error: multiple definition of ‘enum class vk::Result’
   enum class Result
              ^
In file included from test.cpp:2:0:
vk_cpp.h:187:14: error: previous definition here
   enum class Result
              ^
In file included from test.cpp:2:0:
vk_cpp.h: In function ‘std::string vk::getString(vk::Result)’:
vk_cpp.h:24079:22: error: redefinition of ‘std::string vk::getString(vk::Result)’
   inline std::string getString(Result value)
                      ^
In file included from test.cpp:2:0:
vk_cpp.h:215:22: error: ‘std::string vk::getString(vk::Result)’ previously defined here
   inline std::string getString(Result value)

**Comment by mtavenrath** [comment]
@Saulzar, please check if you can still repro using the latest version. We cannot reproduce it.

**Comment by Saulzar** [comment]
Confirm it's no longer happening in the latest version. Cheers
