### ISSUE TITLE
Rename to .hpp

### ISSUE THREAD

**Issue by ioquatix** [nvpro-pipeline/vkcpp#83]
.h is a C header, .hpp is a C++ header. Clang++ sometimes complains about this depending on what warnings you have enabled. Proposed name change to `vulkan.hpp`

**Comment by omaressa** [comment]
@ioquatix  Makes sense. If you actually look at most of the C++ libraries, they do tend to use .hpp rather than .h which is more suitable for C.

**Comment by ioquatix** [comment]
It's not even just a matter of what is more suitable, but that a `.h` file is not technically supposed to contain any C++ code.

**Comment by ioquatix** [comment]
In any case, what I did was copy the file into my project and rename it to `vulkan.hpp` which avoids any compiler warnings.

**Comment by omaressa** [comment]
@ioquatix  I agree, but some c++ projects still tend to use .h extension for header files and I think that will continue to be the case until the compilers actually force people to use .hpp extension only.

**Comment by ioquatix** [comment]
@omaressa Compilers DO force you to use .hpp if you ask for the right warning and make warnings errors :)

**Comment by mtavenrath** [comment]
I agree that changing the extension to .hpp is a good idea. I'm not sure if renaming the file to vulkan.hpp is good since this project is not an official part of Vulkan. Looking at layers (yes, this is not a 'layer' in the sense of Vulkan layers), they tend to start with vk_ which is why we've chosen vk_cpp as name.

**Comment by mtavenrath** [comment]
The header has been renamed to vk_cpp.hpp. Closing bug.

**Comment by ioquatix** [comment]
Awesome. Still think it could do with a better name `vk_cpp.hpp` is pretty confusing. It sort of looks like an implementation file. What about just `vk.hpp`?

**Comment by mtavenrath** [comment]
The project has moved to the KhronosGroup repository and the header has been renamed to vulkan.hpp

**Comment by ioquatix** [comment]
Awesome! That is a great move.
