### ISSUE TITLE
Remove "e" prefix from scoped enumerators

### ISSUE THREAD

**Issue by Ralith** [nvpro-pipeline/vkcpp#84]
Scoped enums provide more than adequate namespace isolation for their enumerators without any extra measures.

**Comment by sinesc** [comment]
If the prefix was removed, several identifiers would begin with a digit, i.e. in ImageType 1D, 2D, 3D. They probably added the general prefix to avoid special cases for this issue.

**Comment by asuessenbach** [comment]
sinesc is exactly right: to prevent special handling for those enumeration values that would start with a digit, we added this 'e' to all enumeration values.

**Comment by Ralith** [comment]
Ah, I see. Thanks for clarifying!
