### ISSUE TITLE
Extension required enum bitpos support

### ISSUE THREAD

**Issue by PistonMiner** [nvpro-pipeline/vkcpp#86]
When attempting to parse an extension enum which is defined as a bitpos as in VK_IMG_filter_cubic, the assertion on [line 1016](https://github.com/nvpro-pipeline/vkcpp/blob/master/VkCppGenerator.cpp#L1016) will fail due to supporting only values and offsets.

**Comment by asuessenbach** [comment]
Fixed with pull request #89.
Closing.
