### ISSUE TITLE
SwapchainCreateInfoKHR imageUsage incorrect assignment

### ISSUE THREAD

**Issue by ocirne23** [nvpro-pipeline/vkcpp#9]
https://github.com/nvpro-pipeline/vkcpp/blob/master/vulkan/vk_cpp.h#L11703

 `SwapchainCreateInfoKHR& imageUsage(ImageUsageFlags imageUsage)`
`{`
`    m_swapchainCreateInfoKHR.imageUsage = static_cast<VkImageUsageFlags>(imageUsage);`
`    return *this;`
`}`

should be

`SwapchainCreateInfoKHR& imageUsage(ImageUsageFlagBits imageUsage)`
`{`
`    m_swapchainCreateInfoKHR.imageUsage = static_cast<VkImageUsageFlagBits>(imageUsage);`
`    return *this;`
`}`

Otherwise calling the function with e.g. 16 will assign 1 to .imageUsage.

**Comment by mtavenrath** [comment]
Fixed
