### ISSUE TITLE
Error on include in Visual Studio 2012

### ISSUE THREAD

**Issue by nickw22** [nvpro-pipeline/vkcpp#90]
Getting this error in a new project in Visual Studio 2012. Base Vulkan works fine

First few errors:-

Error	1	error C2071: 'vk::Flags<BitType,MaskType>::operator MaskType' : illegal storage class	c:\vulkansdk\1.0.5.0\include\vulkan\vk_cpp.h	161
Error	2	error C2071: 'vk::Optional<RefType>::operator bool' : illegal storage class	c:\vulkansdk\1.0.5.0\include\vulkan\vk_cpp.h	196
Error	3	error C3646: 'noexcept' : unknown override specifier	c:\vulkansdk\1.0.5.0\include\vulkan\vk_cpp.h	269

do i need to set something up in compiler options?

**Comment by mtavenrath** [comment]
Unfortunately Visual 2012 does not support the required C++11 features and thus is not supported.
